INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (1,'COORDINADOR EXTENSIONES AULICAS',3),
	 (2,'ADMINISTRATIVA DE SEDE',1),
	 (3,'ADMINISTRATIVO EXTENSIONES AÚLICAS',1),
	 (4,'MAESTRANZA',1),
	 (5,'MANTENIMIENTO',1),
	 (6,'VIGILANCIA',1),
	 (7,'RESPONSABLE MANTENIMIENTO Y PAÑOL',1),
	 (8,'DIRECTOR EXTENSIONES AULICAS',3),
	 (9,'ADMINISTRATIVO DE PAÑOL - EXTENSION AULICA EX-SCAC',1),
	 (10,'ADMINISTRATIVA DIRECTOR DE EXTENSIONES AULICAS',1);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (11,'COORDINADORA EXTENSION AULICA',3),
	 (12,'JEFE PROGRAMA EXTENSION Y VINCULACION',2),
	 (13,'JEFE DE PRORGAMA GABINETE INTERDISCIPLINARIO PARA LA INCLUSIÓN',2),
	 (14,'ADMINISTRATIVA DE SECRETARIA RECURSO HUMANO',4),
	 (15,'ADMINISTRATIVO DE SECRETARIA ACADEMICA',3),
	 (16,'JEFE PROGRAMA DE MANTENIMIENTO EDILICIO Y DE INSTALACIONES',1),
	 (17,'JEFE SUBPROGRAMA COMPRAS Y DESARROLLO DE PROVEEDORES',1),
	 (18,'ADMINISTRATIVO ENCARGADO NAVE TECNICA',1),
	 (19,'ADMINISTRATIVO SECRETARIA DE RECTOR',1),
	 (20,'ADMINISTRATIVO DE PAÑOL ESTETICA',1);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (21,'COORDINADOR TECNICO DE NIVELACION',3),
	 (22,'RESPONSABLE DE PROTOCOLO Y CEREMONIAL',2),
	 (23,'ADMINISTRATIVO SECRETARIA DE EXTENSION Y VINCULACION',2),
	 (24,'JEFA DE PROGRAMA COORDINACION PEDAGOGICA Y FORM. INSTRUCTORES',3),
	 (25,'JEFE DE PROGRAMA HACIENDA',1),
	 (26,'ADMINISTRATIVO PAÑOL',1),
	 (27,'ADMINISTRATIVO SECRETARIA ACADEMICA',3),
	 (28,'COORDINADOR TÉCNICO',3),
	 (29,'ADMINISTRATIVO PROGRAMA COMPRAS Y CONTRATACIONES',1),
	 (30,'ADMINISTRATIVO SUBPROGRAMA SISTEMAS INFORMATICOS Y MANTENIMIENTO DE REDES',1);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (31,'JEFE DE OBRA DE PROGRAMA PROYECTOS Y CONSULTORIA',2),
	 (32,'JEFA DE PROGRAMA DE INSERCION LABORAL AL GRADUADO',2),
	 (33,'RESPONSABLE DE COMUNICACIÓN',2),
	 (34,'SECRETARIO DE EXTENSIÓN Y VINCULACIÓN',2),
	 (35,'JEFE DE SUBPROGRAMA GESTION ALUMNOS',1),
	 (36,'COORDINADOR PROGRAMA PROYECTOS Y CONSULTORIAS',2),
	 (37,'SUPERVISOR DE MAESTRANZA',1),
	 (38,'ADMINISTRATIVO PROGRAMA PROYECTOS Y CONSULTORIAS',2),
	 (39,'JEFA DE PROGRAMA COMPRAS Y CONTRATACIONES',1),
	 (40,'JEFA PROGRAMA ANALISIS Y LIQUIDACION DE HABERES',4);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (41,'ADMINISTRATIVO DE SECRETARIA RECURSO HUMANO',4),
	 (42,'DIRECTOR DE CARRERA',3),
	 (43,'JEFE SUBPROGRAMA ABASTECIMIENTO Y LOGÍSTICA',1),
	 (44,'ADMINISTRATIVO PROGRAMA CONTROL Y ASESORAMIENTO LEGAL',1),
	 (45,'ADMINISTRATIVO GESTION ALUMNOS',1),
	 (46,'ADMINISTRATIVA ENCARGADA NAVE TECNICA',1),
	 (47,'ADMINISTRATIVO PROGRAMADOR DE SERVIDORES',1),
	 (48,'ADMINISTRATIVA ENCARGADA DE EDIFICIO INNOVAR',1),
	 (49,'SECRETARIA DE RECURSOS HUMANOS',4),
	 (50,'ADMINISTRATIVO CALL CENTER',2);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (51,'SECRETARIA ACADÉMICA',3),
	 (52,'JEFE DE PROGRAMA PROYECTOS Y CONSULTORIAS',2),
	 (53,'ADMINISTRATIVO DE SUBPROGRAMA GESTION ALUMNOS',1),
	 (54,'ADMINISTRATIVA ENCARGADA NAVE CREATIVA',1),
	 (55,'JEFE DE SUBPROGRAMA TESORERIA GENERAL',1),
	 (56,'DIRECTORA CARRERA',3),
	 (57,'ADMINISTRATIVO DE RECURSOS HUMANOS',4),
	 (58,'RESPONSABLES HIGIENE Y SEGURIDAD LABORAL',4),
	 (59,'ADMINISTRATIVO DE PROGRAMA CONTROL Y ASESORAMIENTO LEGAL',1),
	 (60,'SECRETARIA GENERAL',1);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (61,'ARQUITECTO',2),
	 (62,'JEFA DE PROGRAMA GESTION DE ALUMNOS',1),
	 (63,'JEFA DE PROGRAMA CONTROL Y ASESORAMIENTO LEGAL',1),
	 (64,'EXTERNA',2),
	 (65,'JEFE DE PROGRAMA PROGRAMACION Y DESARROLLO DE SISTEMAS',1),
	 (66,'RECTOR',1),
	 (67,'ADMINISTRATIVO ENCARGADO EDIFICIO NAVE CREATIVA',1),
	 (68,'JEFA SUBPROGRAMA PRESUPUESTO SISTEMA CONTABLE Y PATRIMONIO',1),
	 (69,'ADMINISTRATIVA DE SECRETARIA GENERAL',1),
	 (70,'JEFE SUBPROGRAMA CONTROL DE AUSENTISMO',4);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (71,'ADMINISTRATIVO PROGRAMA HACIENDA',4),
	 (72,'ADMINISTRATIVO SECRETARIA RECURSOS HUMANOS',4),
	 (73,'COMUNICACION',2),
	 (74,'ADM NIVELACION - ACADEMICA',3),
	 (75,'ADM - CALL CENTER - EXTENSION Y VINCULACION',2),
	 (76,'ARQ PROYECTOS - EXTENSION Y VINCULACION',2),
	 (77,'JEFE SUBPROGRAMA DE PROYECTOS Y CONSULTORIA',2),
	 (78,'JEFE DE MANTENIMIENTO',1),
	 (79,'PAÑOL',1),
	 (80,'ADMINISTRATIVO SECRETARIA GENERAL',1);
INSERT INTO plataforma_upro.areas (id,nombre,secretaria_id) VALUES
	 (81,'JEFE DE SUBPROGRAMA DE MANTENIMIENTO',1),
	 (82,'COORDINADORA',3),
	 (83,'INSTRUCTOR',3),
	 (84,'AUXILIAR',3),
	 (85,'INSTRUCTOR FICA',3);
