INSERT INTO plataforma_upro.secretaria (id,nombre) VALUES
	 (1,'SECRETARIA GENERAL'),
	 (2,'SECRETARIA EXTENSION Y VINCULACION'),
	 (3,'SECRETARIA ACADÉMICA'),
	 (4,'PROVEEDORES EXTERNOS'),
	 (5,'SECRETARIA RECURSO HUMANO');
